version: '3'
services:
  db:
    image: "hub.hamdocker.ir/library/postgres"
    container_name: postgres
    env_file:
      - "./.env"
  manager:
    image: "harleywinston/x-manager:0.1"
    container_name: manager
    restart: always
    env_file:
      - "./.env"
    ports:
      - "3001:3001"
    depends_on:
      - db
