version: '3'
services:
  db:
    image: "hub.hamdocker.ir/library/postgres"
    container_name: postgres
    env_file:
      - "./.dev.env"
  manager:
    image: "hub.hamdocker.ir/cosmtrek/air"
    container_name: manager
    working_dir: "/go/src/github.com/harleywinston/x-manager"
    restart: always
    env_file:
      - "./.dev.env"
    ports:
      - "3000:3000"
    volumes:
      - "/home/harley/go/src/github.com/harleywinston/x-manager:/go/src/github.com/harleywinston/x-manager"
    depends_on:
      - db
